CREATE TABLE `account` (
  `ACT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACT_FIRST_NAME` varchar(50) NULL,
  `ACT_PLAN` varchar(10) NOT NULL,
  `ACT_ADDRESS_LINE1` varchar(250) NULL,
  `ACT_EMAIL` varchar(70) NOT NULL,
  `ACT_PHONE` varchar(15) NOT NULL,
  `ACT_CREATION_DATE` datetime NOT NULL,
  `ACT_NOTIF_EMAIL` varchar(1) NULL,
  `ACT_NOTIF_SMS` varchar(1) DEFAULT NULL,
  `ACT_LAST_NAME` varchar(50) NULL,
  `ACT_LAST_UPDATE` datetime DEFAULT NULL,
  `ACT_COUNTRY` varchar(30) NULL,
  `ACT_AUTO_PULSE_CHECK` varchar(1) NULL,
  `ACT_PULSE_CHECK_FREQ` int(11) NULL,
  `ACT_ADDRESS_LINE2` varchar(250) DEFAULT NULL,
  `ACT_CITY` varchar(80) NULL,
  `ACT_STATE_PROVINCE` varchar(50) NULL,
  `ACT_POSTAL_CODE` varchar(10) NULL,
  `ACT_BIRTH_YEAR` int(11) NULL,
  `ACT_TRAIL_CODE` varchar(1000) NULL,
  PRIMARY KEY(`ACT_ID`));

CREATE TABLE `contact` (
  `CTC_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CTC_FIRST_NAME` varchar(50) NOT NULL,
  `CTC_TYPE` varchar(15) NOT NULL COMMENT 'List of values:\r\nGuardian  = ''GUARDIAN''\r\nInsider  = ''INSIDER''\r\nRecipient = ''RECIPIENT''\r\nInsider & Recipient = ''INSIDER_RECIP''\r\nGuardian & Recipient = ''GUARD_RECIP''\r\n',
  `CTC_COUNTRY` varchar(30) NOT NULL,
  `CTC_EMAIL` varchar(70) NOT NULL,
  `CTC_PHONE` varchar(15) NOT NULL,
  `CTC_PASSWORD` varchar(45) NOT NULL,
  `CTC_LAST_NAME` varchar(50) NOT NULL,
  `CTC_ACCOUNT_ID` int(11) DEFAULT NULL,
  `CTC_MESSAGE` varchar(1000) DEFAULT NULL,
  `CTC_WP_USER_ID` int(11) NOT NULL,
  `CTC_WP_USER_ALIAS` varchar(10) NOT NULL,
  `CTC_CREATION_DATE` datetime NOT NULL,
  `CTC_LAST_UPDATE` datetime DEFAULT NULL,
  `CTC_TRAIL_CODE` varchar(1000) NOT NULL,
  PRIMARY KEY(`CTC_ID`));
