CREATE TABLE `account_audit_trail` (
  `AAT_ACT_ID` INT NULL,
  `AAT_USER_ID` INT NULL,
  `AAT_DATE` DATETIME NULL,
  `AAT_DATA` VARCHAR(1000));

CREATE TABLE `contact_audit_trail` (
  `CAT_CTC_ID` int(11) DEFAULT NOT NULL AUTO_INCREMENT,
  `CAT_USER_ID` int(11) DEFAULT NULL,
  `CAT_DATE` datetime DEFAULT NULL,
  `CAT_DATA` varchar(1000) DEFAULT NULL
PRIMARY KEY (`CAT_CTC_ID`));


