DELIMITER $$
CREATE TRIGGER account_update_trigger
AFTER UPDATE
ON account FOR EACH ROW
BEGIN
    INSERT INTO account_audit_trail(AAT_ACT_ID, AAT_USER_ID, AAT_DATE, AAT_DATA)
    VALUES(NEW.ACT_ID, NEW.ACT_USER_ID, CURRENT_TIMESTAMP, NEW.ACT_TRAIL_CODE);
END$$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER contact_update_trigger
AFTER UPDATE
ON contact FOR EACH ROW
BEGIN
    INSERT INTO contact_audit_trail(CAT_CTC_ID, CAT_USER_ID, CAT_DATE, CAT_DATA)
    VALUES(NEW.CTC_ID, NEW.CTC_WP_USER_ID, CURRENT_TIMESTAMP, NEW.CTC_TRAIL_CODE);
END$$
DELIMITER;

DELIMITER $$
CREATE TRIGGER contact_insert_trigger
AFTER INSERT
ON contact FOR EACH ROW
BEGIN
    INSERT INTO contact_audit_trail(CAT_CTC_ID, CAT_USER_ID, CAT_DATE, CAT_DATA)
    VALUES(NEW.CTC_ID, NEW.CTC_WP_USER_ID, CURRENT_TIMESTAMP, NEW.CTC_TRAIL_CODE);
END$$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER file_insert_trigger
AFTER INSERT
ON files FOR EACH ROW
BEGIN
    INSERT INTO file_audit_trail(FAT_FIL_ID, FAT_USER_ID, FAT_DATE, FAT_DATA)
    VALUES(NEW.	FIL_ID, NEW.FIL_ACCOUNT_ID, CURRENT_TIMESTAMP, NEW.FIL_TRAIL_CODE);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER file_delete_trigger
AFTER DELETE
ON files FOR EACH ROW
BEGIN
    INSERT INTO file_audit_trail(FAT_FIL_ID, FAT_USER_ID, FAT_DATE, FAT_DATA)
    VALUES(OLD.	FIL_ID, OLD.FIL_ACCOUNT_ID, CURRENT_TIMESTAMP, OLD.FIL_TRAIL_CODE);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER schedule_update_trigger
AFTER UPDATE
ON schedule FOR EACH ROW
BEGIN
    INSERT INTO schedule_audit_trail(SAT_FIL_ID, SAT_USER_ID, SAT_DATE, SAT_DATA)
    VALUES(NEW.SCH_ID, NEW.SCH_ACCOUNT_ID, CURRENT_TIMESTAMP, NEW.SCH_TRAIL_CODE);
END$$
DELIMITER;

DELIMITER $$
CREATE TRIGGER schedule_insert_trigger
AFTER INSERT
ON schedule FOR EACH ROW
BEGIN
    INSERT INTO schedule_audit_trail(SAT_FIL_ID, SAT_USER_ID, SAT_DATE, SAT_DATA)
    VALUES(NEW.SCH_ID, NEW.SCH_ACCOUNT_ID, CURRENT_TIMESTAMP, NEW.SCH_TRAIL_CODE);
END$$
DELIMITER;

DELIMITER $$
CREATE TRIGGER schedule_delete_trigger
AFTER DELETE
ON schedule FOR EACH ROW
BEGIN
    INSERT INTO schedule_audit_trail(SAT_FIL_ID, SAT_USER_ID, SAT_DATE, SAT_DATA)
    VALUES(OLD.SCH_ID, OLD.SCH_ACCOUNT_ID, CURRENT_TIMESTAMP, OLD.SCH_TRAIL_CODE);
END$$
DELIMITER;
