DELIMITER $$
CREATE TRIGGER account_update_trigger
AFTER UPDATE
ON account FOR EACH ROW
BEGIN
    INSERT INTO account_audit_trail(AAT_USER_ID, AAT_DATE, AAT_DATA)
    VALUES(OLD.ACT_USER_ID, CURRENT_TIMESTAMP, OLD.ACT_TRAIL_CODE);
END$$
DELIMITER ;
